### ISSUE TITLE
filter type select failed

### ISSUE THREAD

**Issue by ifitllc** [pratik227/quasar-qgrid#99]
When the value has null, and the column filter type is defined as select, it will fail:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toString')
    at QGrid.vue:520:28
    at Array.filter (<anonymous>)
    at Proxy.getColumnOptions (QGrid.vue:520:28)
    at QGrid.vue:101:61
    at renderFnWithContext (runtime-core.esm-bundler.js:868:19)
    at hSlot (quasar.esm.js:2034:7)
    at Proxy.<anonymous> (quasar.esm.js:31583:12)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5720:34)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)

**Comment by pratik227** [comment]
Hi @ifitllc,

I will check.

**Comment by pratik227** [comment]
Hi @ifitllc,

I think the issue is with the field. I think the field value that you have given is not there in the data.

**Comment by pratik227** [comment]
Closing this issue bcz of inactivity
